# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Release & publish

on:
  create:
      tags:
        - v*

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - name: Use Node.js 10.x
      uses: actions/setup-node@v2
      with:
        node-version: 10.x
        cache: 'npm'

    - name: Install tools
      run: npm install -g tfx-cli typescript

    - name: Install dependencies
      run: npm ci
    
    - name: Run unit tests
      run: npm run test -- --ci
      env:
        CI: true

    - name: Package vsix file 
      run: npm run pack

    - name: Publish extension
      shell: bash
      env:
        VSS_PAT: ${{ secrets.VSS_PAT }}
      run: |
        tfx extension publish --manifest-globs vss-extension.json --vsix vsts-changed-files-multibranch.vsix --token wrvpj24quofh5hohlwzzrx4dnjmrdi2qqqhgfxrmd4r27o5y2g6a